### PR TITLE
Ch1 src cleanup: Coarray fix, readability & style

### PR DESCRIPTION
**Pull request by zbeekman**
Supersedes PR #3 

- Fix duplicate unordered write to same coindex of same variable from unordered execution segments
- Try to fix Travis-CI builds

### CODE REVIEW

**Review by milancurcic — APPROVED** [review]

**Comment by zbeekman** [comment]
FYI, the linux build may be silently failing; or at least it isn't building the coarray code yet.

**Comment by milancurcic** [comment]
@zbeekman I enabled the coarray tests in Travis, but it can't find `cafrun` once it gets to it. Do we perhaps need to add it to the PATH?

**Comment by zbeekman** [comment]
We need to install OpenCoarrays on the Travis-CI ubuntu image. I was working on that, but had to put it down for "real" work 😐. You'll need to install it into user space. (Unless you want to bite the bullet and set `sudo: true` but that will slow the linux builds. (May not be an issue since MacOS builds are so backlogged on Travis-CI anyway...) Best place to do that is in the if statement in the `before_instal:` block. Add an else branch (for non macOS) and then you could use the installer script, but I recommend a direct CMake invocation.

Something like:

```
wget ...
tar xzvf ...
cd ...
export FC=gfortran
export CC=gcc
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=${HOME}/.local
make install -j
export PATH="${HOME}/.local/bin:$PATH"
cd ../..
```

**Comment by milancurcic** [comment]
Gotcha, OK, I had assumed that opencoarrays were installed...will get back to this in the next few days. Not super critical at this early stage..

**Pull request merged**
